file(MAKE_DIRECTORY "${WORK}")
function(run expected)
  execute_process(COMMAND "${FOLIAGE}" ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT result EQUAL expected)
    message(FATAL_ERROR "Unexpected status ${result}, expected ${expected}: ${ARGN}\n${output}\n${error}")
  endif()
endfunction()
run(0 --help)
run(0 --version)
run(0 nodes --json)
run(0 materials --json)
run(1 materials --typo)
run(0 describe radial)
run(1 describe imaginary)
run(1 nodes --typo)
run(1 generate)
run(1 "${SOURCE}/graphs/tree.json" --seed 2147483648)
run(1 "${SOURCE}/graphs/tree.json" --seed 1oops)
run(1 "${SOURCE}/graphs/tree.json" --out)
run(1 "${SOURCE}/graphs/tree.json" --max-vertices 12)
run(0 validate "${SOURCE}/graphs/rose.json" --json)
run(0 generate "${SOURCE}/graphs/rose.json" --out "${WORK}/rose" --seed -123 --json)
execute_process(COMMAND "${FOLIAGE}" - --out "${WORK}/stdin" --json INPUT_FILE "${SOURCE}/graphs/plant.json" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "stdin failed: ${output}\n${error}")
endif()
if(NOT EXISTS "${WORK}/stdin/plant.glb" OR NOT EXISTS "${WORK}/stdin/plant.obj" OR NOT EXISTS "${WORK}/stdin/plant.mtl")
  message(FATAL_ERROR "missing exported files")
endif()

run(0 lods --json)
run(1 lods --typo)
run(0 "${SOURCE}/graphs/lod-cards.json" --out "${WORK}/lods" --json)
run(0 "${SOURCE}/graphs/lod-cards.json" --out "${WORK}/single-lod" --lod LOD1 --json)
run(0 "${SOURCE}/graphs/lod-cards.json" --out "${WORK}/base-lod" --no-lods --json)
run(1 "${SOURCE}/graphs/lod-cards.json" --lod missing)
run(1 "${SOURCE}/graphs/lod-cards.json" --lod LOD1 --no-lods)
run(1 validate "${SOURCE}/graphs/lod-cards.json" --no-lods)
if(NOT EXISTS "${WORK}/lods/lod-cards-LOD2.glb" OR NOT EXISTS "${WORK}/lods/lods.json" OR EXISTS "${WORK}/single-lod/lod-cards.glb" OR EXISTS "${WORK}/base-lod/lod-cards-LOD1.glb")
  message(FATAL_ERROR "LOD output selection contract failed")
endif()

run(0 growth --json)
run(1 growth --typo)
run(0 "${SOURCE}/graphs/growth-tree.json" --out "${WORK}/growth" --json)
run(0 "${SOURCE}/graphs/growth-tree.json" --out "${WORK}/one-step" --growth-step 4 --no-lods --json)
run(0 "${SOURCE}/graphs/growth-tree.json" --out "${WORK}/one-step-lod" --growth-step 4 --lod LOD1 --json)
run(0 "${SOURCE}/graphs/growth-tree.json" --out "${WORK}/mature-only" --no-growth --no-lods --json)
run(1 "${SOURCE}/graphs/growth-tree.json" --growth-step 9)
run(1 "${SOURCE}/graphs/growth-tree.json" --growth-step -1)
run(1 "${SOURCE}/graphs/growth-tree.json" --growth-step 4 --no-growth)
run(1 "${SOURCE}/graphs/tree.json" --growth-step 0)
run(1 validate "${SOURCE}/graphs/growth-tree.json" --no-growth)
if(EXISTS "${WORK}/growth/growth-tree-G00.glb" OR NOT EXISTS "${WORK}/growth/growth.json" OR NOT EXISTS "${WORK}/growth/growth-tree-G08.glb" OR EXISTS "${WORK}/one-step/growth-tree.glb" OR NOT EXISTS "${WORK}/one-step-lod/growth-tree-LOD1-G04.glb" OR EXISTS "${WORK}/mature-only/growth-tree-G01.glb")
  message(FATAL_ERROR "Growth output selection contract failed")
endif()

run(0 "${SOURCE}/graphs/weeping-willow.json" --out "${WORK}/willow-cards" --lod Cards --json)
if(NOT EXISTS "${WORK}/willow-cards/weeping-willow-Cards.glb" OR EXISTS "${WORK}/willow-cards/weeping-willow.glb")
  message(FATAL_ERROR "Willow packed generation selection failed")
endif()

run(0 card-bakes --json)
run(1 card-bakes --typo)
run(0 "${SOURCE}/graphs/card-bake.json" --out "${WORK}/baked-cards" --card-bake Strand --json)
run(1 "${SOURCE}/graphs/card-bake.json" --card-bake missing)
run(1 "${SOURCE}/graphs/card-bake.json" --card-bake Strand --no-lods)
run(1 "${SOURCE}/graphs/card-bake.json" --card-bake Strand --growth-step 0)
run(1 validate "${SOURCE}/graphs/card-bake.json" --card-bake Strand)
if(NOT EXISTS "${WORK}/baked-cards/card-bake-strand.glb" OR NOT EXISTS "${WORK}/baked-cards/card-bake-strand.cardbake/manifest.json" OR EXISTS "${WORK}/baked-cards/card-bake-source.glb")
  message(FATAL_ERROR "CardBake selection failed")
endif()

run(0 exports --json)
run(1 exports --typo)
run(1 "${SOURCE}/graphs/growth-exports.json" --export)
run(1 "${SOURCE}/graphs/growth-exports.json" --export missing)
run(1 "${SOURCE}/graphs/growth-exports.json" --export GeometryStages --growth-step 0)
run(1 "${SOURCE}/graphs/growth-exports.json" --export GeometryStages --no-lods)
run(1 "${SOURCE}/graphs/growth-exports.json" --export GeometryStages --card-bake Strand)
run(1 validate "${SOURCE}/graphs/growth-exports.json" --export GeometryStages)
run(0 "${SOURCE}/graphs/growth-exports.json" --export GeometryStages --out "${WORK}/stages" --json)
run(0 "${SOURCE}/graphs/growth-exports.json" --export CardStages --out "${WORK}/stages" --json)
if(NOT EXISTS "${WORK}/stages/strand-geometry-stages/G004/model.glb" OR NOT EXISTS "${WORK}/stages/strand-card-stages/G004/model.cardbake/manifest.json")
  message(FATAL_ERROR "Named growth export selection failed")
endif()
