#!/usr/bin/env python3
"""Generate reference documentation from the CLI catalog."""
import argparse
import json
import subprocess
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--foliage', type=Path, default=Path('build/foliageutil'))
    args = parser.parse_args()
    catalog = json.loads(subprocess.check_output([str(args.foliage.resolve()), 'nodes', '--json'], text=True))
    root = Path(__file__).resolve().parents[1]
    (root / 'docs/nodes.json').write_text(json.dumps(catalog, indent=2) + '\n')
    lines = ['# Node reference', '', 'Generated by `python3 tools/update_docs.py`. The executable catalog is authoritative.', '', 'All angles are degrees; geometry uses meters and right-handed Y-up coordinates.', 'Every node uses direct parameters beside `op`. Unknown parameters fail validation.', 'References are node names. Query `foliageutil describe OP` for machine-readable controls.', '']
    for name, node in catalog.items():
        lines += ['## ' + name, '', node['description'], '', '**Output:** ' + node['output'] + '.', '', '| Parameter | Type | Default | Controls |', '| --- | --- | --- | --- |']
        for field, rule in node['parameters'].items():
            default = json.dumps(rule['default']) if 'default' in rule and rule['default'] is not None else 'required' if rule.get('required') else 'omitted'
            detail = rule['description']
            if 'min' in rule:
                detail += f" Bounds: {rule['min']:g}..{rule['max']:g}."
            if 'enum' in rule:
                detail += ' Values: ' + ', '.join(rule['enum']) + '.'
            if 'kinds' in rule:
                detail += ' Accepts: ' + ', '.join(rule['kinds']) + '.'
            lines += [f"| `{field}` | {rule['type']} | `{default}` | {detail.replace('|', '/')} |"]
        lines += ['']
    (root / 'docs/NODES.md').write_text('\n'.join(lines))
    for command in ['lods', 'growth', 'card-bakes', 'exports']:
        fields = json.loads(subprocess.check_output([str(args.foliage.resolve()), command, '--json'], text=True))
        (root / f'docs/{command}.json').write_text(json.dumps(fields, indent=2) + '\n')
    materials = json.loads(subprocess.check_output([str(args.foliage.resolve()), 'materials', '--json'], text=True))
    (root / 'docs/materials.json').write_text(json.dumps(materials, indent=2) + '\n')
    lines = ['# Material reference', '', 'Generated by `python3 tools/update_docs.py` from `foliageutil materials --json`.', '', 'These fields belong in each named entry of the root `materials` object.', 'Unknown fields and invalid bounds fail validation, including unused materials.', '', 'Core PBR fields export as glTF materials. Nonzero translucency or subsurface', 'exports a versioned `extras.foliageutil` object. The Blender preview adapter', 'applies those optical controls automatically; other viewers need their own adapter.', 'OBJ/MTL and the solid-color Filament helper do not implement these optics.', '', 'Gem transmission, IOR and volume controls use standard glTF extensions.', 'They are separate from foliage translucency and need a compatible renderer;', 'see [rocks and crystals](MINERALS.md) for examples and Unity shader limitations.', '', '| Parameter | Type | Default | Controls |', '| --- | --- | --- | --- |']
    for name, rule in materials.items():
        detail = rule['description']
        if 'min' in rule:
            detail += f" Bounds: {rule['min']:g}..{rule['max']:g}."
        if 'enum' in rule:
            detail += ' Values: ' + ', '.join(rule['enum']) + '.'
        default = json.dumps(rule['default']) if rule.get('default') is not None else 'omitted'
        lines.append(f"| `{name}` | {rule['type']} | `{default}` | {detail.replace('|', '/')} |")
    (root / 'docs/MATERIALS.md').write_text('\n'.join(lines) + '\n')


if __name__ == '__main__':
    main()
